### ISSUE TITLE
I can't run on my  computer,please tell me how to run on my computer

### ISSUE THREAD

**Issue by AliceLanniste** [nbarkhina/MarioHTML#5]
I like your project.  I `git clone` your project and follow your readme.  `tsc` complier `.ts` files. finally I open the index.html. But  It only   shows  static  web paage.So please tell me how to run on my computer
![捕获](https://user-images.githubusercontent.com/17617116/118208985-4d503f00-b49a-11eb-9299-30abc198caf1.PNG)

**Comment by nbarkhina** [comment]
hi @AliceLanniste can you please show me what console errors you are getting? open up your chrome dev tools and check what the log is saying. that will give us a clue as to the problem.

**Comment by nbarkhina** [comment]
@AliceLanniste were you able to resolve this issue and can I close this?
